### ISSUE TITLE
Running tests when there are no test classes should not return an error

### ISSUE THREAD

**Issue by dschach** [salesforcecli/plugin-apex#3]
If we set up a new project from a template that runs all local Apex tests on a PR, the Github workflow fails at the beginning because there are no tests to run.

Running something like `sfdx force:apex:test:run -c -r human -l RunLocalTests -d ./tests/apex -w 20` should not return an error if there are no tests in the org. It should just give a notification that there are no tests and exit gracefully.

**Comment by dschach** [comment]
Bump?

**Comment by mshanemc** [comment]
hey, CLI has taken over this plugin by the VSCode team.

I'm going to turn issues off since it's all supposed to go through https://github.com/forcedotcom/cli/issues.

If you can still replicate it, either open an issue either there or on https://github.com/forcedotcom/salesforcedx-apex/issues
